version: '3.1'

services:

  postgres:
    image: postgres
    container_name: pgdev
#    environment:
#      POSTGRES_USER: ninja
#      POSTGRES_PASSWORD: ninja
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
